# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyshen/Desktop/v9-cpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyshen/Desktop/v9-cpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyshen/Desktop/v9-cpu/CMakeFiles /home/zyshen/Desktop/v9-cpu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyshen/Desktop/v9-cpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ALL

# Build rule for target.
ALL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ALL
.PHONY : ALL

# fast build rule for target.
ALL/fast:
	$(MAKE) -f CMakeFiles/ALL.dir/build.make CMakeFiles/ALL.dir/build
.PHONY : ALL/fast

#=============================================================================
# Target rules for targets named v9_cpu

# Build rule for target.
v9_cpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 v9_cpu
.PHONY : v9_cpu

# fast build rule for target.
v9_cpu/fast:
	$(MAKE) -f CMakeFiles/v9_cpu.dir/build.make CMakeFiles/v9_cpu.dir/build
.PHONY : v9_cpu/fast

#=============================================================================
# Target rules for targets named xc

# Build rule for target.
xc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xc
.PHONY : xc

# fast build rule for target.
xc/fast:
	$(MAKE) -f CMakeFiles/xc.dir/build.make CMakeFiles/xc.dir/build
.PHONY : xc/fast

root/bin/c.o: root/bin/c.c.o
.PHONY : root/bin/c.o

# target to build an object file
root/bin/c.c.o:
	$(MAKE) -f CMakeFiles/xc.dir/build.make CMakeFiles/xc.dir/root/bin/c.c.o
.PHONY : root/bin/c.c.o

root/bin/c.i: root/bin/c.c.i
.PHONY : root/bin/c.i

# target to preprocess a source file
root/bin/c.c.i:
	$(MAKE) -f CMakeFiles/xc.dir/build.make CMakeFiles/xc.dir/root/bin/c.c.i
.PHONY : root/bin/c.c.i

root/bin/c.s: root/bin/c.c.s
.PHONY : root/bin/c.s

# target to generate assembly for a file
root/bin/c.c.s:
	$(MAKE) -f CMakeFiles/xc.dir/build.make CMakeFiles/xc.dir/root/bin/c.c.s
.PHONY : root/bin/c.c.s

root/bin/em.o: root/bin/em.c.o
.PHONY : root/bin/em.o

# target to build an object file
root/bin/em.c.o:
	$(MAKE) -f CMakeFiles/v9_cpu.dir/build.make CMakeFiles/v9_cpu.dir/root/bin/em.c.o
.PHONY : root/bin/em.c.o

root/bin/em.i: root/bin/em.c.i
.PHONY : root/bin/em.i

# target to preprocess a source file
root/bin/em.c.i:
	$(MAKE) -f CMakeFiles/v9_cpu.dir/build.make CMakeFiles/v9_cpu.dir/root/bin/em.c.i
.PHONY : root/bin/em.c.i

root/bin/em.s: root/bin/em.c.s
.PHONY : root/bin/em.s

# target to generate assembly for a file
root/bin/em.c.s:
	$(MAKE) -f CMakeFiles/v9_cpu.dir/build.make CMakeFiles/v9_cpu.dir/root/bin/em.c.s
.PHONY : root/bin/em.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... v9_cpu"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xc"
	@echo "... ALL"
	@echo "... root/bin/c.o"
	@echo "... root/bin/c.i"
	@echo "... root/bin/c.s"
	@echo "... root/bin/em.o"
	@echo "... root/bin/em.i"
	@echo "... root/bin/em.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

